# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
#   - jekyll-remote-theme

# title: Power-grid-analysis
# description: this is a project for DSC 80 at UCSD.

# remote_theme: pages-themes/slate@v0.2.0
# plugins:
#   - jekyll-remote-theme

# title: Power-grid-analysis
# description: this is a project for DSC 80 at UCSD.

remote_theme: hydecorp/[email protected]

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: Storms, Prices, and the Power Grid
description: "DSC 80 project on U.S. power outages."

url: "https://arnavgoel03.github.io"
baseurl: "/Power-grid-analysis"
