# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
#   - jekyll-remote-theme

# title: Power-grid-analysis
# description: this is a project for DSC 80 at UCSD.

remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: Power-grid-analysis
description: this is a project for DSC 80 at UCSD.
